### ISSUE TITLE
Game lock and console spam when trying to add Nulcearcraft ores.

### ISSUE THREAD

**Issue by Fungie2134** [kyeiti/UndergroundBiomesConstructs#26]
https://hastebin.com/dudumaruxu.md : Logs
https://paste.dimdev.org/isilazuxum.mccrash : another crash
Config file : 

[
  {
    "internalOreName": "nuclearcraft:ore",
    "meta": 4,
    "overlay": "undergroundbiomes:blocks/overlays/modernmetals/uranium",
    "oreDirectories": []
  }
]

**Comment by kyeiti** [comment]
Looks like NuclearCraft and UB keep pushing the responsiblity for finding the light value of the block on each other. I'll add a config option for the light value, since I don't know how else to resolve this. (Light value determines if the block emits light and how much - e.g. Thermal Foundation's Destabilized Redstone emits a bit of light.)

Your config from above will then change to this:
```JSON
[
  {
    "internalOreName": "nuclearcraft:ore",
    "meta": 4,
    "overlay": "undergroundbiomes:blocks/overlays/modernmetals/uranium",
    "oreDirectories": [],
    "lightValue": 0
  }
]
```

**Comment by Aang23** [comment]
Fixed. I'll close this now.
Thanks !
